any1/neatvnc

src/server.c

Include sys/param.h for MIN definition

---

examples/Makefile
examples/png-server.c
src/pngfb.c

The first fixes a build issue observed when building examples. The second is more cosmetic.

Fix examples

---

include/fb.h
meson.build
src/damage.c
src/display.c
src/fb.c
src/pixels.c
src/raw-encoding.c
src/server.c
src/stream.c
src/tight.c
src/zrle.c

Several changes which share the common goal to use `-Wmissing-prototypes` by default.

Use static for functions not used outside this compile unit

---

src/server.c

Fix trivial build warnings when building without TLS support.

fix build warnings when building without tls

---

meson.build

Depends on https://github.com/any1/aml/pull/5. Downstream may pass `-Ddefault_library=static` (or `-Dneatvnc:default_library=static`) to avoid packaging dependencies.
See also https://mesonbuild.com/Build-targets.html

Allow consumers to link statically

---

meson.build
meson_options.txt

- ~~add option for cpu optimizations~~
- add option for sys/std.h
- ~~remove aml as subdirectory and make proper dependency~~
~~This helps in packaging to gentoo as CPU specific optimizations will not work on all ARM/x86_64 platforms.~~
Signed-off-by: Aisha Tammy <gentoo@aisha.cc>

add proper build options (helps for building a package)

---

include/neatvnc.h
src/server.c

Use an extended getaddrinfo_unix which will treat any absolute path
(i.e. address starting with '/') as a place to bind a UNIX domain
socket. Store the socket path in the main nvnc structure to allow for
cleanup on closure. Closes #1.

support UNIX sockets

---

src/server.c

Same as https://github.com/any1/wlvncc/pull/6. Given  `c_std=gnu11` in meson.build and predefined `__BYTE_ORDER__` in server.c let's rely more on the compiler being GCC-compatible than libc being glibc-compatible.

Unbreak build on FreeBSD

---

src/fb.c

I got
```
/usr/bin/ld: subprojects/neatvnc/libneatvnc.so.0.0.0.p/src_fb.c.o: in function `nvnc__fb_free':
/home/harmth/gits/wayvnc/build/../subprojects/neatvnc/src/fb.c:187: undefined reference to `gbm_bo_destroy'
collect2: error: ld returned 1 exit status
[68/71] Compiling C object wayvnc.p/src_main.c.o
ninja: build stopped: subcommand failed.
```
while trying to compile neatvnc on Debian Bullseye aarch64.

Don't call gbm symbols when they are not available

---

src/server.c

Regressed by f20ffb5e1efe. `IPPROTO_TCP` requires `<netinet/in.h>` while `TCP_NODELAY` requires `<netinet/tcp.h>`, both on Linux (glibc, musl) and on BSDs (DragonFly, FreeBSD, NetBSD, OpenBSD). Likely missed due to header bootlegging. To investigate on Linux (where it builds fine "as is") inject `#error` into `<netinet/in.h>` to let compiler show intermediate headers.
See also https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/netinet_in.h.html
```c
$ meson setup /tmp/neatvnc_build
$ meson compile -C /tmp/neatvnc_build
[...]
src/server.c:1119:17: error: use of undeclared identifier 'IPPROTO_TCP'
setsockopt(fd, IPPROTO_TCP, TCP_NODELAY, &one, sizeof(one));
^
```

Unbreak build on BSDs

---

include/neatvnc.h
src/server.c

Add a function nvnc_client_supports_cursor() to enable the API user to make an informed decision whether nvnc_set_cursor() can be expected to make the client draw the cursor, or whether it has to be rendered into the framebuffer.

Allow to query client-side cursor support

---

meson.build

`src/log.c` uses `av_log_set_level()` and `av_log_set_callback()` from libavutil if `HAVE_LIBAVUTIL` is set. This causes a build failure if libavutils development packages are installed, but the other dependencies for h264 are not.

Add missing dependency on libavutil if found

---

src/server.c

If a framebuffer is resized directly after connecting, it causes a null pointer to be dereferenced. This avoids that.

don't resize an encoder if it is not set

---

src/murmurhash.c

Fix two -Wimplicit-fallthrough warnings in the murmurhash function:
```
../src/murmurhash.c: In function 'murmurhash':
../src/murmurhash.c:71:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
71 |     case 3: k ^= (tail[2] << 16);
|             ~~^~~~~~~~~~~~~~~~~~
../src/murmurhash.c:72:5: note: here
72 |     case 2: k ^= (tail[1] << 8);
|     ^~~~
../src/murmurhash.c:72:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
72 |     case 2: k ^= (tail[1] << 8);
|             ~~^~~~~~~~~~~~~~~~~
../src/murmurhash.c:74:5: note: here
74 |     case 1:
|     ^~~~
```

Fix fallthrough warnings in murmurhash

---

include/common.h
include/neatvnc.h
src/server.c

- Record peer hostname for each connected client
- Record authenticated username for each connected client
Both of these are best-effort, and may not be available for all clients.

Record client hostname and username

---

include/neatvnc.h
src/server.c

This allows the user to terminate any given nvnc_client connection at
any time.
Signed-off-by: Jim Ramsay <i.am@jimramsay.com>

Add nvnc_client_close API

---

src/stream.c

If a TLS stream is closed by the remote VNC client, `stream__remote_closed()` must be called to signal the server.

stream: Fix remote closing TLS connection

---

examples/draw.c
include/common.h
include/desktop-layout.h
include/neatvnc.h
include/rfb-proto.h
meson.build
src/desktop-layout.c
src/server.c

Implement minimal desktop resizing support and demonstrate it in the draw example, tested with TigerVNC.
This uses the [ExtendedDesktopSize](https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#7713extendeddesktopsize-pseudo-encoding) pseudo-encoding to let clients know that they may issue [SetDesktopSize](https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#7410setdesktopsize) messages. Neat VNC reports those via the `nvnc_desktop_size_fn` callback. Right now the callback is not prepared for multi-display support (the screen layout structures are not passed in) and it can't report back the _out-of-resources_ or _request-forwarded (async)_ status codes - a return value of `true` maps to _no-error_ and `false` maps to _resize-administratively-prohibited_.

Desktop resizing

---

meson.build

Fixes the following Meson warning:
```
WARNING: You should add the boolean check kwarg to the run_command call.
It currently defaults to false,
but it will default to true in future releases of meson.
See also: https://github.com/mesonbuild/meson/issues/9300
```

Fix Meson warning about missing check kwarg in run_command() calls

---

include/pixels.h
src/cursor.c
src/damage-refinery.c
src/fb.c
src/pixels.c
src/raw-encoding.c
src/tight.c
src/zrle.c
test/test-pixels.c

Summary:
- Added additional field "byte_stride"
- Add byte stride to fb which is the width of a row in bytes (not pixels)
- fb size is no longer just using 4 for pixel size
- added new function to handle 24 bit source format
- addressing into the source data will now use bits per pixel to calculate offsets
- use similar addressing formula as in tight.c, no longer is the bpp constant to 4.

NVidia Tight encoder fix

---

include/common.h
include/neatvnc.h
src/server.c

Tested with a systemd .socket unit in https://github.com/any1/wayvnc/pull/310
Supersedes: https://github.com/any1/neatvnc/pull/69
Required by: https://github.com/any1/wayvnc/issues/227, https://github.com/any1/wayvnc/pull/310

server: Support opening on an existing socket fd

---

include/common.h
include/rfb-proto.h
src/server.c

This patch implements the extended clipboard pseudo-encoding, specifically only the text format. The appeal of this protocol is that it specifies that the text must be UTF-8 rather than Latin-1. In addition, the text is encoded by zlib which can reduce the length of the freeze that would occur when pushing a large clipboard update over a low-bandwidth link so long as the text is compressible.
The library user/wayvnc doesn't need to do anything to enable the protocol. The protocol is request-based, but I integrated it with the existing interface by simply caching the response in a buffer in nvnc_send_cut_text which can be sent when the client sends a request. Alternatively, the API could be extended in some way and wayvnc's data control code would need to adapt to it.
The protocol states …

Extended Clipboard pseudo-encoding (UTF-8 text)

---

include/common.h
include/rfb-proto.h
src/server.c

Support sending continuous framebuffer updates when requested via the [EnableContinuousUpdates](https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#enablecontinuousupdates) message.

Add continuous update support

---

src/server.c

At least in systemds case, unlinking breaks socket based (re)activation.

server: Do not unlink an externally managed fd

---

src/enc/tight.c

If refinery is disabled, pixels at the tile its boundaries are not considered by the tight encoder. This can trigger the assert(self->n_rects > 0); when only pixels at the boundary are damaged, or can cause those lines not to be updated. Remove the -1 from y2, x2 to fix the size of the tile.
To trigger the assert, refinery must be either disabled in code or  ENCODER_IMPL_FLAG_IGNORES_DAMAGE must be set. https://github.com/jhofstee/qneatvnc/tree/trigger-tight-assert will trigger the assert and behaves as expected with this patch.
I have read and understood CONTRIBUTING.md

enc: tight: Fix the size of the tile

---

src/server.c

Since n_pending_request is decremented after client_send_led_state is done, it should be incremented when the LED status is queued. Especially when continues updates are used this could lead to a single FramebufferUpdateRequest tiggering only a LED status message and not the framebuffer update itself and hence noVNC e.g. never showed the initial display.

Send queued message when switching to continuous updates

---

src/stream/gnutls.c
src/stream/tcp.c

The stream req's payload will be unreffed upon the req being removed from the send queue and freed. But if a stream req cannot be created in stream_send in the first place then the payload should be unreffed before returning -1.

stream: Unref payload after failing to create req

---

src/server.c

If the last character is a carriage return, we would have read one byte out of bounds. 'in_len' cannot be 0 at this point. When 'in' is pointing to the last character, 'in_len' is 1.

server: Fix off by one error in crlf_to_lf

---

src/server.c

If key_code_fn is not set, key_fn will be called with keysym in the case of QEMU-style events.
Follow up of https://github.com/any1/neatvnc/pull/139

server: Notify with keysym if key_code_fn is not set

---

meson.build
meson_options.txt
src/crypto/random.c
src/logging.c

Right now neatvnc doesn't build out of the box in OSX.
* header files of libdrm are needed, but there is no way to build libdrm in OSX.
* OSX doesn't support threads.h (but _Thread_local)
* getrandom is linux only
Regarding arc4random: In the past this call seemed to be a [security issue](https://security.stackexchange.com/questions/85601/is-arc4random-secure-enough), however at least [FreeBSD and OpenBSD](https://man.freebsd.org/cgi/man.cgi?query=arc4random) changed their implementation, OSX changed since version 10.12 (according to man page)

OSX Build Fixes
